apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonapp-deployment
spec:
  selector:
    matchLabels:
      app: pythonapp
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: pythonapp
    spec:
      containers:
      - name: pythonapp
        image: 0905062524/pythonapp:1.0
        ports:
        - name: app-port
          containerPort: 80